community/openjdk-mandrel: fix build with python 3.14
Replace the use of the `pipes.quote` with `shlex.quote` to fix build
with python >=3.13. The `pipes` module was removed in python 3.13.

Error found on the 3.24 builders.

```
Traceback (most recent call last):
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx_enter.py", line 44, in <module>
    mx._main_wrapper()
    ~~~~~~~~~~~~~~~~^^
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx.py", line 18386, in _main_wrapper
    main()
    ~~~~^^
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx.py", line 18268, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx.py", line 3784, in _discover_suites
    _register_visit(primary)
    ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx.py", line 3782, in _register_visit
    s._load()
    ~~~~~~~^^
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx.py", line 1764, in _load
    self._load_extensions()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mx-6.27.3/mx.py", line 2261, in _load_extensions
    mod = __import__(extensionsName)
  File "/home/buildozer/aports/community/openjdk-mandrel/src/mandrel-23.0.0.0/substratevm/mx.substratevm/mx_substratevm.py", line 38, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

Ref: https://gitlab.alpinelinux.org/alpine/aports/-/issues/18143